### ISSUE TITLE
Bug in htab_delete?

### ISSUE THREAD

**Issue by craigbarnes** [rofl0r/htab#1]
The `htab_delete()` function appears to remove entries by setting `key` to `0`/`NULL`. Unless I'm missing something, that seems like it would break the assumptions that the rest of the code relies upon, with regards to open addressing/quadratic probing. Shouldn't it instead be replacing the key with a "tombstone"?

**Comment by craigbarnes** [comment]
I think the following test case should demonstrate the problem:

```c
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "hsearch.h"

static char *xstrdup(const char *str)
{
    char *dup = strdup(str);
    assert(dup);
    return dup;
}

int main(void)
{
    const size_t n = 8000;
    char key[16];
    struct htab *h = htab_create(8192);
    assert(h);

    // Fill table with strings 0..n
    for (unsigned int i = 0; i < n; i++) {
        snprintf(key, sizeof(key), "%u", i);
        int r = htab_insert(h, xstrdup(key), HTV_N(42));
        assert(r == 1);
        // Ensure newly inserted entry can be found
        assert(htab_find(h, key));
    }

    // Remove entries, in the same order they were inserted
    for (unsigned int i = 0; i < n; i++) {
        snprintf(key, sizeof(key), "%u", i);
        htab_delete(h, key);
        // Check that all remaining entries in the table can be found
        for (unsigned int j = i + 1; j < n; j++) {
            snprintf(key, sizeof(key), "%u", j);
            assert(htab_find(h, key));
        }
    }

    htab_destroy(h);
    return 0;
}
```

```
$ gcc -O2 -g -Wall -Wextra -fsanitize=address,undefined bug.c hsearch.c
$ ./a.out
a.out: bug.c:37: main: Assertion `htab_find(h, key)' failed.
Aborted (core dumped)
```

Some of the probing chains are being broken after keys are removed, which causes `htab_find()` to return as if the key was never inserted.

With tombstones, `htab_find_item()` would need to be modified so that it continues probing if `e->item.key == tombstone`. The original code from musl didn't need to worry about this, since the API doesn't support removal.

**Comment by rofl0r** [comment]
thanks for pointing this out. according to the info on https://research.cs.vt.edu/AVresearch/hashing/deletion.php we have 2 options here:

```
 Two possible solutions to this problem are

-    Do a local reorganization upon deletion to try to shorten the average path length. For example, after deleting a key, continue to follow the probe sequence of that key and swap records further down the probe sequence into the slot of the recently deleted record (being careful not to remove any key from its probe sequence). This will not work for all collision resolution policies.

-    Periodically rehash the table by reinserting all records into a new hash table. Not only will this remove the tombstones, but it also provides an opportunity to place the most frequently accessed records into their home positions.
```

looks like option 1 is more in the spirit of the original implementation in that it doesn't require allocation of a new temporary object, and probably also takes less code to deal with it. fortunately we can add the tombstone without additional storage requirements by checking whether key is null and hash value e.g. 0xdeadc0de.

btw your testcase should use strdup for the key insertion, as otherwise all keys will point to the same stack address.

**Comment by craigbarnes** [comment]
> thanks for pointing this out

No worries.

> according to the info on https://research.cs.vt.edu/AVresearch/hashing/deletion.php we have 2 options here

I've been using a hash table implementation loosely based on the musl code in a few of my projects for a while and I opted for the second approach to that problem. Although the rehash is not done "periodically" per se, but rather when the number of occupied entries plus the number of tombstones reaches the maximum load factor.

I also rehash at the _same size_ if the number of tombstones is greater than the number of active entries when the load factor is reached (purely to flush out the tombstones). With the current `resize()` function, it's quite easy to patch it in such a way that it _does_ properly clear out a build-up of tombstones, but still ends up doubling the table size on every rehash, even when the number of real entries stays constant (e.g. when removing the oldest entry each time a new one is inserted, in a hash table used as part of a fixed-sized FIFO cache).

> looks like option 1 is more in the spirit of the original implementation in that it doesn't require allocation of a new temporary object, and probably also takes less code to deal with it.

That option does seem to have quite a few advantages, although I'm not too sure about the specifics.

> fortunately we can add the tombstone without additional storage requirements by checking whether key is null and hash value e.g. 0xdeadc0de

Yeah, that seems like a good option. I just set the `key` to some known address (e.g. a global `static char tombstone[8]`) and do a pointer comparison when probing (or iterating), but that idea seems like it'd work just as well.

Once you add tombstones, every probing loop has to be updated, and unlike before, they all need slightly different logic. For example insertions have to _replace_ tombstones, lookups have to continue probing beyond them, iterators have to ignore them (or perhaps not; depending on how you implement them), so it's quite an invasive change.

> btw your testcase should use strdup for the key insertion, as otherwise all keys will point to the same stack address.

Yeah, my bad. I spent a while thinking of a way to demonstrate the problem and forgot to fix that.

**Comment by rofl0r** [comment]
finally got around to dig into this.
i've produced a patch that seems to work so far and can execute your testcase successfully: http://ix.io/2SIE (this version only fixes the issue at hand, i'll investigate whether the resize func should be called at all or not to rehash at some point).
however it seems super-slow: execution takes about 30 secs with CPU throttled to 800mhz, 10 second-ish at 2 GHz.
@craigbarnes you said you also have a hashtable based on musl, how long does yours take to execute this test ? (also do you have a link to your hashtable?)

**Comment by rofl0r** [comment]
i did some measurements with perf and it turned out that most of the time was spent in snprintf. changing the code to use a custom utoa() routine, the test finishes almost instantly.

```c
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "hsearch.h"

static char *xstrdup(const char *str)
{
    char *dup = strdup(str);
    assert(dup);
    return dup;
}

void utoa(unsigned number, char* buffer) {
        int lentest, len = 0, i, start = 0;

        lentest = number;
        do {
                len++;
                lentest /= 10;
        } while(lentest);
        buffer[start+len] = 0;
        do {
                i = number % 10;
                buffer[start+len - 1] = '0' + i;
                number -= i;
                len -= 1;
                number /= 10;
        } while (number);
}

int main(void)
{
    const size_t n = 8000;
    char key[16];
    struct htab *h = htab_create(16384);
    assert(h);

    // Fill table with strings 0..n
    for (unsigned int i = 0; i < n; i++) {
	utoa(i, key);
        int r = htab_insert(h, xstrdup(key), HTV_N(42));
        assert(r == 1);
        // Ensure newly inserted entry can be found
        assert(htab_find(h, key));
    }

    // Remove entries, in the same order they were inserted
    for (unsigned int i = 0; i < n; i++) {
	utoa(i, key);
        htab_delete(h, key);
        // Check that all remaining entries in the table can be found
        for (unsigned int j = i + 1; j < n; j++) {
		utoa(j, key);
            assert(htab_find(h, key));
        }
    }

    htab_destroy(h);
    return 0;
}
```

**Comment by craigbarnes** [comment]
> however it seems super-slow: execution takes about 30 secs with CPU throttled to 800mhz, 10 second-ish at 2 GHz.

Yeah, the test case was just the first thing I managed to throw together that triggered the problem. Having it complete quickly is indeed a nice improvement, to allow quickly verifying the problem no longer exists.

> i've produced a patch that seems to work so far and can execute your testcase successfully: http://ix.io/2SIE (this version only fixes the issue at hand, i'll investigate whether the resize func should be called at all or not to rehash at some point).

I haven't done any further testing or put much thought into how this fix changes things, but I wonder what would happen if the table becomes completely filled with tombstones? Wouldn't that lead to an infinite loop in the probing sequence, when looking up a key that doesn't exist in the table?

The `resize()` [condition](https://github.com/rofl0r/htab/blob/d36687a2a5f3297621109b2dbc6c6b26273c823c/hsearch.c#L168) currently doesn't take tombstones into account, even though they contribute towards the load factor in some respects.

**Comment by rofl0r** [comment]
thanks for your thoughtful analysis!

you're right, having all free slots marked as dead does indeed cause an endless loop:

```c
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "hsearch.h"

static char *xstrdup(const char *str)
{
    char *dup = strdup(str);
    assert(dup);
    return dup;
}

void utoa(unsigned number, char* buffer) {
        int lentest, len = 0, i, start = 0;

        lentest = number;
        do {
                len++;
                lentest /= 10;
        } while(lentest);
        buffer[start+len] = 0;
        do {
                i = number % 10;
                buffer[start+len - 1] = '0' + i;
                number -= i;
                len -= 1;
                number /= 10;
        } while (number);
}

static size_t keyhash(char *k)
{
	unsigned char *p = (void *)k;
	size_t h = 0;

	while (*p)
		h = 31*h + *p++;
	return h;
}


#define TESTSIZE 8

static char* notorious[TESTSIZE];

static void prep() {
	srand(0);
	char buf[16];
	size_t filled = 0;
	while(filled < TESTSIZE) {
		utoa(rand(), buf);
		size_t idx = keyhash(buf) & (TESTSIZE-1);
		if(!notorious[idx]) {
			notorious[idx] = xstrdup(buf);
			++filled;
		}
	}
}

int main(void)
{
	struct htab *h = htab_create(TESTSIZE);
	size_t i;
	assert(h);

	prep();
	for(i=0; i<TESTSIZE; ++i) {
		char *key = notorious[i];
		printf("[%zu] = \"%s\"\n", i, key);
		int r = htab_insert(h, key, HTV_N(42));
		assert(r == 1);
		// Ensure newly inserted entry can be found
		assert(htab_find(h, key));
		htab_delete(h, key);
	}

	htab_find(h, "looooop");

	return 0;
}
```

it appears the only effective countermeasure is indeed to resize if used+dead > threshold and not allow further insertions in OOM situtation. i got a correct looking patch in the works, but will do some more testing.

**Comment by rofl0r** [comment]
after some hours of testing, i'm pretty confident that the committed fix is a reasonable solution.
though it's well possible i've overlooked yet another complication...
if you have further feedback, i'd love to hear it. thanks!
